### ISSUE TITLE
Datapack crash on latest version

### ISSUE THREAD

**Issue by BugmanBugman** [Mlodziak00/Skeletal-Remains-Fabric#3]
[22:44:04] [main/WARN] [minecraft/Main]: Failed to load datapacks, can't proceed                                                                                                                                                              with server load. You can either fix your datapacks or reset to vanilla with --                                                                                                                                                             safeMode
java.util.concurrent.ExecutionException: com.google.gson.JsonParseException: Err                                                                                                                                                             or(s) loading registries:

Error(s) loading registry forge:biome_modifier:
Not a JSON object: ["#minecraft:is_ocean","#minecraft:is_deep_ocean"]
Not a JSON object: ["#minecraft:is_ocean","#minecraft:is_deep_ocean"]
        at: file "data/skeletalremains/biome_modifier/spawn_sunken.json"
Not a JSON object: ["#minecraft:has_structure/swamp_hut","minecraft:swamp","mine                                                                                                                                                             craft:mangrove_swamp"]
Not a JSON object: ["#minecraft:has_structure/swamp_hut","minecraft:swamp","mine                                                                                                                                                             craft:mangrove_swamp"]
        at: file "data/skeletalremains/biome_modifier/spawn_swamped.json"

        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.ja                                                                                                                                                             va:396) ~[?:?] {re:mixin}
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:207                                                                                                                                                             3) ~[?:?] {re:mixin}
        at net.minecraft.server.Main.main(Main.java:182) ~[server-1.19.2-2022080                                                                                                                                                             5.130853-srg.jar%23617!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHa                                                                                                                                                             ndleAccessor.java:104) ~[?:?] {}
        at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?] {}
        at net.minecraftforge.fml.loading.targets.CommonServerLaunchHandler.lamb                                                                                                                                                             da$launchService$0(CommonServerLaunchHandler.java:29) ~[fmlloader-1.19.2-43.2.14                                                                                                                                                             .jar%2367!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServi                                                                                                                                                             ceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler                                                                                                                                                             .java:53) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler                                                                                                                                                             .java:71) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.                                                                                                                                                             0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.                                                                                                                                                             0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchCo                                                                                                                                                             nsumer.java:26) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchCo                                                                                                                                                             nsumer.java:23) [modlauncher-10.0.8.jar%2354!/:?] {}
        at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.j                                                                                                                                                             ava:141) [bootstraplauncher-1.1.2.jar:?] {}
Caused by: com.google.gson.JsonParseException: Error(s) loading registries:

Error(s) loading registry forge:biome_modifier:
Not a JSON object: ["#minecraft:is_ocean","#minecraft:is_deep_ocean"]
Not a JSON object: ["#minecraft:is_ocean","#minecraft:is_deep_ocean"]
        at: file "data/skeletalremains/biome_modifier/spawn_sunken.json"
Not a JSON object: ["#minecraft:has_structure/swamp_hut","minecraft:swamp","mine                                                                                                                                                             craft:mangrove_swamp"]
Not a JSON object: ["#minecraft:has_structure/swamp_hut","minecraft:swamp","mine                                                                                                                                                             craft:mangrove_swamp"]
        at: file "data/skeletalremains/biome_modifier/spawn_swamped.json"

        at com.alcatrazescapee.cyanide.codec.MixinHooks.readRegistries(MixinHook                                                                                                                                                             s.java:74) ~[cyanide-forge-1.19.2-3.0.1.jar%23419!/:3.0.1] {re:mixin,re:classloa                                                                                                                                                             ding}
        at net.minecraft.resources.RegistryOps.redirect$dci000$loadCollectingErr                                                                                                                                                             ors(RegistryOps.java:534) ~[server-1.19.2-20220805.130853-srg.jar%23617!/:?] {re                                                                                                                                                             :mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:AP                                                                                                                                                             P:cyanide.common.mixins.json:RegistryOpsMixin,pl:mixin:A}
        at net.minecraft.resources.RegistryOps.m_206817_(RegistryOps.java:32) ~[                                                                                                                                                             server-1.19.2-20220805.130853-srg.jar%23617!/:?] {re:mixin,pl:accesstransformer:                                                                                                                                                             B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cyanide.common.mixins.json                                                                                                                                                             :RegistryOpsMixin,pl:mixin:A}
        at net.minecraft.resources.RegistryOps.m_206813_(RegistryOps.java:25) ~[                                                                                                                                                             server-1.19.2-20220805.130853-srg.jar%23617!/:?] {re:mixin,pl:accesstransformer:                                                                                                                                                             B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:cyanide.common.mixins.json                                                                                                                                                             :RegistryOpsMixin,pl:mixin:A}
        at net.minecraft.server.Main.lambda$main$2(Main.java:160) ~[server-1.19.                                                                                                                                                             2-20220805.130853-srg.jar%23617!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at net.minecraft.server.WorldLoader.m_214362_(WorldLoader.java:24) ~[ser                                                                                                                                                             ver-1.19.2-20220805.130853-srg.jar%23617!/:?] {re:classloading}
        at net.minecraft.server.WorldStem.m_214415_(WorldStem.java:18) ~[server-                                                                                                                                                             1.19.2-20220805.130853-srg.jar%23617!/:?] {re:mixin,re:classloading}
        at net.minecraft.server.Main.lambda$main$3(Main.java:158) ~[server-1.19.                                                                                                                                                             2-20220805.130853-srg.jar%23617!/:?] {re:classloading,re:mixin,pl:mixin:A}
        at net.minecraft.Util.m_214652_(Util.java:775) ~[server-1.19.2-20220805.                                                                                                                                                             130853-srg.jar%23617!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:ac                                                                                                                                                             cesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_prioriti                                                                                                                                                             es.UtilMixin,pl:mixin:APP:yungsbridges.mixins.json:SuppressLogMixin,pl:mixin:APP                                                                                                                                                             :bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:APP:mixin.imdlib-whisper                                                                                                                                                             woods.json:UtilMixin,pl:mixin:A}
        at net.minecraft.Util.m_214679_(Util.java:770) ~[server-1.19.2-20220805.                                                                                                                                                             130853-srg.jar%23617!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:ac                                                                                                                                                             cesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:perf.thread_prioriti                                                                                                                                                             es.UtilMixin,pl:mixin:APP:yungsbridges.mixins.json:SuppressLogMixin,pl:mixin:APP                                                                                                                                                             :bettermineshafts.mixins.json:SuppressLogMixin,pl:mixin:APP:mixin.imdlib-whisper                                                                                                                                                             woods.json:UtilMixin,pl:mixin:A}
        at net.minecraft.server.Main.main(Main.java:157) ~[server-1.19.2-2022080                                                                                                                                                             5.130853-srg.jar%23617!/:?] {re:classloading,re:mixin,pl:mixin:A}
        ... 11 more

**Comment by Mlodziak00** [comment]
Oh my bad, accidentally set it to #minecraft:(is_biome) instead of #forge:(is_biome).
I'll have all that fixed within the next 24 hours.

**Comment by Mlodziak00** [comment]
Fixed the issue, all that was happening was me misspelling the tags, the upcoming update (It's being approved) has all those problems fixed
